USE Webtech;

ALTER TABLE User_Group
ADD CONSTRAINT FOREIGN KEY (User_ID) REFERENCES User (User_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE User_Group
ADD CONSTRAINT FOREIGN KEY (Group_ID) REFERENCES Groups (Group_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE User_Modul
ADD CONSTRAINT FOREIGN KEY (User_ID) REFERENCES User (User_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE User_Modul
ADD CONSTRAINT FOREIGN KEY (Modul_ID) REFERENCES Modul (Modul_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE; 

ALTER TABLE Modul_Group
ADD CONSTRAINT FOREIGN KEY (Modul_ID) REFERENCES Modul (Modul_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE Modul_Group
ADD CONSTRAINT FOREIGN KEY (Group_ID) REFERENCES Groups (Group_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE Termine
ADD CONSTRAINT FOREIGN KEY (Ersteller_ID) REFERENCES User (User_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE Termine_Group
ADD CONSTRAINT FOREIGN KEY (Termin_ID) REFERENCES Termine (Termin_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE Termine_Group
ADD CONSTRAINT FOREIGN KEY (Group_ID) REFERENCES Groups (Group_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE;
