USE Webtech;

ALTER TABLE student_group
ADD CONSTRAINT FOREIGN KEY (matrikel_nr) REFERENCES student (matrikel_nr)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE student_group
ADD CONSTRAINT FOREIGN KEY (group_id) REFERENCES groups (group_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE student_modul
ADD CONSTRAINT FOREIGN KEY (matrikel_nr) REFERENCES student (matrikel_nr)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE student_modul
ADD CONSTRAINT FOREIGN KEY (modul_id) REFERENCES modul (modul_id)
ON DELETE RESTRICT
ON UPDATE CASCADE; 

ALTER TABLE modul_group
ADD CONSTRAINT FOREIGN KEY (modul_id) REFERENCES modul (modul_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE modul_group
ADD CONSTRAINT FOREIGN KEY (group_id) REFERENCES groups (group_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE modul_mitarbeiter
ADD CONSTRAINT FOREIGN KEY (modul_id) REFERENCES modul (modul_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE modul_mitarbeiter
ADD CONSTRAINT FOREIGN KEY (personal_id) REFERENCES hs_mitarbeiter (personal_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE termine
ADD CONSTRAINT FOREIGN KEY (ersteller_ID) REFERENCES hs_mitarbeiter (personal_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE termine
ADD CONSTRAINT FOREIGN KEY (ersteller_ID) REFERENCES student (matrikel_nr)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE termine_teilnehmer
ADD CONSTRAINT FOREIGN KEY (termin_id) REFERENCES termine (termin_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE termine_teilnehmer
ADD CONSTRAINT FOREIGN KEY (teilnehmer_ID) REFERENCES hs_mitarbeiter (personal_id)
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE termine_teilnehmer
ADD CONSTRAINT FOREIGN KEY (teilnehmer_ID) REFERENCES student (matrikel_nr)
ON DELETE RESTRICT
ON UPDATE CASCADE;