USE Webtech;

ALTER TABLE User_Group
ADD CONSTRAINT FOREIGN KEY (User_ID) REFERENCES User (ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE User_Group
ADD CONSTRAINT FOREIGN KEY (Group_ID) REFERENCES Groups (Group_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE User_Modul
ADD CONSTRAINT FOREIGN KEY (User_ID) REFERENCES User (ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE User_Modul
ADD CONSTRAINT FOREIGN KEY (Modul_ID) REFERENCES Modul (Modul_ID)
ON DELETE CASCADE
ON UPDATE CASCADE; 

ALTER TABLE Groups
ADD CONSTRAINT FOREIGN KEY (Modul_ID) REFERENCES Modul (Modul_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE Termine
ADD CONSTRAINT FOREIGN KEY (Ersteller_ID) REFERENCES User (ID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE Termine
ADD CONSTRAINT FOREIGN KEY (Group_ID) REFERENCES Groups (Group_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE InviteCodes
ADD CONSTRAINT FOREIGN KEY (Modul_ID) REFERENCES Modul (Modul_ID)
ON DELETE CASCADE
ON UPDATE CASCADE;